DEFAULT_SMTP_HOST = "smtp.qiye.aliyun.com"
DEFAULT_SMTP_PORT_SSL = 465
DEFAULT_IMAP_HOST = "imap.qiye.aliyun.com"
DEFAULT_IMAP_PORT_SSL = 993

DEFAULT_RATE_LIMIT_SECONDS = 1.0
AUTO_CONNECT_RETRY_SECONDS = 60.0
SCHEDULE_CHECK_INTERVAL_MS = 15_000

MEBIBYTE = 1024 * 1024
MAX_ATTACHMENT_BYTES = 15 * MEBIBYTE
MAX_INLINE_IMAGE_BYTES = 5 * MEBIBYTE
MAX_EMAIL_ASSET_BYTES = 18 * MEBIBYTE
